apiVersion: v1
kind: Service
metadata:
  labels:
    service-lscrocha1-blog-site-key-lb: service-lscrocha1-blog-site-value-lb
  name: service-name-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - name: service-port-name
    port: 80
    protocol: TCP
  selector:
    lscrocha1-blog-key: lscrocha1-blog-site-value